import requests
from bs4 import BeautifulSoup
from markdownify import markdownify as md
import re

outputInput = [
('Canada, English', 'https://www.apple.com/ca/legal/internet-services/icloud/en/terms.html'),
('Canada, français', 'https://www.apple.com/ca/fr/legal/internet-services/icloud/cafr/terms.html'),
('United States, English', 'https://www.apple.com/legal/internet-services/icloud/us-en/terms.html'),
('United States, Español', 'https://www.apple.com/legal/internet-services/icloud/us-es/terms.html'),
('Anguilla, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Antigua and Barbuda, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Argentina, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Bahamas, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Barbados, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Belize, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Belize, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Bolivia, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Brasil, português', 'https://www.apple.com/br/legal/internet-services/icloud/br/terms.html'),
('British Virgin Islands, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Cayman Islands, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Chile, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Colombia, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Costa Rica, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Dominica, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Ecuador, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('El Salvador, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Grenada, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Guatemala, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Guyana, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Honduras, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Jamaica, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('México, Español', 'https://www.apple.com/mx/legal/internet-services/icloud/la/terms.html'),
('Montserrat, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Nicaragua, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Panamá, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Paraguay, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Perú, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('República Dominicana, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('St. Kitts and Nevis, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('St. Lucia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('St. Vincent & The Grenadines, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Suriname, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Suriname, Nederlands', 'https://www.apple.com/legal/internet-services/icloud/nl/terms.html'),
('Trinidad and Tobago, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Turks & Caicos, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Uruguay, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Venezuela, Español', 'https://www.apple.com/legal/internet-services/icloud/la/terms.html'),
('Afghanistan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Australia, English', 'https://www.apple.com/au/legal/internet-services/icloud/en/terms.html'),
('Bhutan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Brunei, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Cambodia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('China mainland, English', 'https://www.apple.com.cn/legal/internet-services/icloud/en/gcbd-terms.html'),
('Fiji, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Hong Kong, English', 'https://www.apple.com/hk/en/legal/internet-services/icloud/en/terms.html'),
('Indonesia, Bahasa Indonesia', 'https://www.apple.com/legal/internet-services/icloud/id/terms.html'),
('Kyrgyzstan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Laos, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Macau, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Malaysia, Bahasa Melayu', 'https://www.apple.com/legal/internet-services/icloud/my/terms.html'),
('Malaysia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Micronesia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Mongolia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Myanmar, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Nauru, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Nepal, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('New Zealand, English', 'https://www.apple.com/nz/legal/internet-services/icloud/en/terms.html'),
('Pakistan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Palau, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Papua New Guinea, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Philippines, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Singapore, English', 'https://www.apple.com/sg/legal/internet-services/icloud/en/terms.html'),
('Solomon Islands, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Sri Lanka, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Tajikistan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Tonga, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Turkmenistan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Uzbekistan, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Vanuatu, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Việt Nam, Tiếng Việt', 'https://www.apple.com/legal/internet-services/icloud/vn/terms.html'),
('Кыргызстан, русский', 'https://www.apple.com/legal/internet-services/icloud/ru/terms.html'),
('Таджикистан, русский', 'https://www.apple.com/legal/internet-services/icloud/ru/terms.html'),
('Туркменистан, русский', 'https://www.apple.com/legal/internet-services/icloud/ru/terms.html'),
('ไทย, ภาษาไทย', 'https://www.apple.com/th/legal/internet-services/icloud/th/terms.html'),
('대한민국, 한국어', 'https://www.apple.com/kr/legal/internet-services/icloud/kr/terms.html'),
('中国大陆, 简体中文', 'https://www.apple.com.cn/legal/internet-services/icloud/cn_si/gcbd-terms.html'),
('台灣, 繁體中文', 'https://www.apple.com/tw/legal/internet-services/icloud/cn_tr/terms.html'),
('日本, 日本語', 'https://www.apple.com/jp/legal/internet-services/icloud/jp/terms.html'),
('Albania, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Albania, Shqiptar', 'https://www.apple.com/legal/internet-services/icloud/al/terms.html'),
('Armenia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Azərbaycan, Azəri', 'https://www.apple.com/legal/internet-services/icloud/az/terms.html'),
('België, Nederlands', 'https://www.apple.com/benl/legal/internet-services/icloud/nl/terms.html'),
('Belgique, français', 'https://www.apple.com/befr/legal/internet-services/icloud/fr/terms.html'),
('Bosnia-Herz., English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Česko, Čeština', 'https://www.apple.com/legal/internet-services/icloud/cz/terms.html'),
('Cyprus, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Danmark, dansk', 'https://www.apple.com/dk/legal/internet-services/icloud/dk/terms.html'),
('Deutschland, deutsch', 'https://www.apple.com/de/legal/internet-services/icloud/de/terms.html'),
('Eesti, Eestlane', 'https://www.apple.com/legal/internet-services/icloud/ee/terms.html'),
('España, Español', 'https://www.apple.com/es/legal/internet-services/icloud/es/terms.html'),
('France, français', 'https://www.apple.com/fr/legal/internet-services/icloud/fr/terms.html'),
('Georgia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Hrvatska, hrvatski', 'https://www.apple.com/legal/internet-services/icloud/hr/terms.html'),
('Ireland, English', 'https://www.apple.com/ie/legal/internet-services/icloud/en/terms.html'),
('Ísland, íslenska', 'https://www.apple.com/legal/internet-services/icloud/is/terms.html'),
('Italia, italiano', 'https://www.apple.com/it/legal/internet-services/icloud/it/terms.html'),
('Kosovo, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Kosovo, shqiptar', 'https://www.apple.com/legal/internet-services/icloud/al/terms.html'),
('Latvija, latviešu', 'https://www.apple.com/legal/internet-services/icloud/lv/terms.html'),
('Lietuva, lietuviškai', 'https://www.apple.com/legal/internet-services/icloud/lt/terms.html'),
('Luxembourg, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Magyarország, magyar', 'https://www.apple.com/legal/internet-services/icloud/hu/terms.html'),
('Malta, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Moldova, Română', 'https://www.apple.com/legal/internet-services/icloud/ro/terms.html'),
('Montenegro, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Nederland, Nederlands', 'https://www.apple.com/nl/legal/internet-services/icloud/nl/terms.html'),
('Norge, norsk', 'https://www.apple.com/no/legal/internet-services/icloud/no/terms.html'),
('Österreich, deutsch', 'https://www.apple.com/at/legal/internet-services/icloud/de/terms.html'),
('Polska, polski', 'https://www.apple.com/pl/legal/internet-services/icloud/terms-pl.html'),
('Portugal, português', 'https://www.apple.com/pt/legal/internet-services/icloud/pt/terms.html'),
('România, română', 'https://www.apple.com/legal/internet-services/icloud/ro/terms.html'),
('Schweiz, deutsch', 'https://www.apple.com/chde/legal/internet-services/icloud/de/terms.html'),
('Serbia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Slovenija, slovenščina', 'https://www.apple.com/legal/internet-services/icloud/si/terms.html'),
('Slovensko, slovensky', 'https://www.apple.com/legal/internet-services/icloud/sk/terms.html'),
('Suisse, français', 'https://www.apple.com/chfr/legal/internet-services/icloud/fr/terms.html'),
('Suomi, suomi', 'https://www.apple.com/fi/legal/internet-services/icloud/fi/terms.html'),
('Sverige, svenska', 'https://www.apple.com/se/legal/internet-services/icloud/se/terms.html'),
('Türkiye, Türkçe', 'https://www.apple.com/tr/legal/internet-services/icloud/tr/terms.html'),
('Ukraine, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('United Kingdom, English', 'https://www.apple.com/uk/legal/internet-services/icloud/en/terms.html'),
('Ελλάδα, Ελληνικά', 'https://www.apple.com/legal/internet-services/icloud/gr/terms.html'),
('България, български', 'https://www.apple.com/legal/internet-services/icloud/bg/terms.html'),
('Македонски јазик', 'https://www.apple.com/legal/internet-services/icloud/mk/terms.html'),
('Россия, Русский', 'https://www.apple.com/ru/legal/internet-services/icloud/ru/terms.html'),
('Україна, українська', 'https://www.apple.com/legal/internet-services/icloud/uk/terms.html'),
('Հայաստան, հայերեն', 'https://www.apple.com/legal/internet-services/icloud/am/terms.html'),
('Algeria, الجزائر', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Angola, português', 'https://www.apple.com/legal/internet-services/icloud/pt/terms.html'),
('Bahrain, البحرين', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Benin, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Bénin, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Botswana, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Burkina-Faso, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Burkina-Faso, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Cabo Verde, português', 'https://www.apple.com/legal/internet-services/icloud/pt/terms.html'),
('Cameroon, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Cameroun, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Cape Verde, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Chad, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Chad, أللغة العربية', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Congo, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Congo, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Cote d’Ivoire, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Cote d’Ivoire, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Democratic Republic of Congo, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Egypt, مصر', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Eswatini, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Gabon, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Gabon, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Gambia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Ghana, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Guinea-Bissau, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Guinea-Bissau, português', 'https://www.apple.com/legal/internet-services/icloud/pt/terms.html'),
('India, English', 'https://www.apple.com/in/legal/internet-services/icloud/en/terms.html'),
('Iraq, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Iraq, ٱلْعِرَاق', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Israel, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Jordan, الأردن', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Kenya, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Kuwait, دولة الكويت', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Lebanon, لبنان', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Liberia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Libya, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Libya, دولة ليبيا', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Madagascar, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Malawi, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Maldives, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Mali, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Maroc, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Maroc, المملكة المغربية', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Mauritania, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Mauritania, موريتانيا', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Mozambique, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Mozambique, português', 'https://www.apple.com/legal/internet-services/icloud/pt/terms.html'),
('Namibia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Niger, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Oman, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Palestinian Territories, العربية', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Qatar, قطر', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('République démocratique du Congo, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Rwanda, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Sao Tome and Principe, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Sao Tome e Principe, português', 'https://www.apple.com/legal/internet-services/icloud/pt/terms.html'),
('Saudi Arabia, المملكة العربية السعودية', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Sénégal, français', 'https://www.apple.com/legal/internet-services/icloud/fr/terms.html'),
('Seychelles, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Sierra Leone, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('South Africa, English', 'https://www.apple.com/za/legal/internet-services/icloud/en/terms.html'),
('Tanzania, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Tunisia, الجمهورية التونسية', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Uganda, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('United Arab Emirates, الإمارات العربية المتحدة', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Yemen, ٱلْيَمَن', 'https://www.apple.com/legal/internet-services/icloud/ar/terms.html'),
('Zambia, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
('Zimbabwe, English', 'https://www.apple.com/legal/internet-services/icloud/en/terms.html'),
    ]


for (name, url) in outputInput:
    markdown = ''
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    main = soup.find("main")
    document = main.find("div", class_="document-wrapper")
    markdown = md(str(document))
    output = markdown.rstrip("\n")
    output = re.sub(r'\n\s*\n', '\n\n', output)
    with open(name+".md", "w") as file:
        file.write(str(output))